language: node_js
node_js:
  - '12'
dist: trusty
sudo: false

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

branches:
  only:
    -master

before_script:
  - npm install

stages:
  - name: Lint
    script: npm run lint
  - name: Test
    script: npm run test-build
  - name: Build
    if: branch master
    script: npm run build -- --prod
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $TRAVIS_DEPLOY_TOKEN
      keep_history: true
      local_dir: ./dist/factorio-lab
      repo: factoriolab/factoriolab.github.io
      target_branch: master
      on:
        branch: master
