language: node_js
node_js:
  - '12'
dist: trusty
sudo: false

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng lint
  - npm run test-build
  - npm run build -- --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_DEPLOY_TOKEN
  keep_history: true
  local_dir: ./dist/factorio-lab
  repo: factoriolab/factoriolab.github.io
  target_branch: master
  on:
    branch: master
