language: node_js
node_js:
  - '12'
dist: trusty
sudo: false

addons:
  chrome: stable
  
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN

before_script:
  - npm install

jobs:
  include:
    - stage: lint
      name: "Run Linting"
      script: npm run lint
    - stage: test
      name: "Run Tests"
      script: npm run test-build
    - stage: codecov
      name: "Upload Code Coverage"
    - stage: build
      name: "Build and Deploy"
      script: npm run build -- --prod
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $TRAVIS_DEPLOY_TOKEN
        keep_history: true
        local_dir: ./dist/factorio-lab
        repo: factoriolab/factoriolab.github.io
        target_branch: master
        on:
          branch: master

stages:
  - lint
  - test
  - name: codecov
    if: branch = master
  - name: build
    if: branch = master
