language: node_js
node_js:
  - '12'
dist: trusty
sudo: false

addons:
  chrome: stable

before_script:
  - npm install

jobs:
  include:
    - stage: test
      name: "Run Tests"
      script:
        - npm run lint
        - npm run test-build
        - npm run codecov
    - stage: build
      name: "Build and Deploy"
      script: npm run build -- --prod
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./dist/factorio-lab
        repo: factoriolab/factoriolab.github.io
        target_branch: master
        on:
          branch: master

stages:
  - test
  - name: build
    if: branch = master
