name: prod
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build -- -c=production
      - name: Copy index to list
        run: cp dist/browser/index.html dist/browser/list.html
      - name: Copy index to flow
        run: cp dist/browser/index.html dist/browser/flow.html
      - name: Copy index to 404
        run: cp dist/browser/index.html dist/browser/404.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: factoriolab/factoriolab.github.io
          branch: main
          folder: dist/browser
          clean: true
