name: staging
on:
  push:
    branches: [fay]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build -- -c=staging

      # - name: Copy index to 404
      #   run: cp dist/browser/index.html dist/browser/404.html

      - name: Deploy to server
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Set up SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Rsync build artifacts to the server
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" dist/browser/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"

          # Clean up
          rm -rf ~/.ssh/id_rsa
