name: staging
on:
  pull_request:
    branches: [main]
jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
        if: env.DEPLOY == 'true'
      - name: Run build
        run: npm run build -- -c=staging
        if: env.DEPLOY == 'true'
      - name: Copy index to routes
        run: |
          cp dist/browser/index.html dist/browser/list.html
          cp dist/browser/index.html dist/browser/flow.html
          cp dist/browser/index.html dist/browser/data.html
          cp dist/browser/index.html dist/browser/404.html
        if: env.DEPLOY == 'true'
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: env.DEPLOY == 'true'
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: factoriolab/staging
          branch: main
          folder: dist/browser
          clean: true
