name: staging
on:
  pull_request:
    branches: [main]
jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build -- -c=staging
      - name: Semantic release
        run: npx semantic-release
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: factoriolab/staging
          branch: main
          folder: dist/browser
          clean: true
      - name: Discord webhook test
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.TEST_WEBHOOK_URL }}
          content: Hello webhook
