name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run prettier
      - name: Run linting
        run: npm run lint-build
      - name: Run tests
        run: npm run test-build
      - uses: codecov/codecov-action@v3
